#!/bin/bash

./acheck $1

if [ $? -eq 0 ]
then
  ITEM=$1
  shift
  bash $ITEM "$@"
else
  exit 1
fi

# ----Attest-0.1.0------------------------------------------------------------------------ #
#  signed                                                                                  #
#  2018-12-01 11:54:50                                                                     #
# ---------------------------------------------------------------------------------------- #
#  4Y5thZrc8vUovesri55/SaCb+0hmn4tH0mG/7uQGMTt0AllXptMU2bIeIn4mbT8OTDRaSlcSmIMh86ZFzPblvq  #
#  eUp2Srisv7UyRj/tnBbbA4mGM6haGeqLxRD8PhIePxEBNqbRNBAV1ZWHcLGOUMZjJlzRKne3fTN5kjrYJE3/ik  #
#  ZhPvKwJtUIzFnmxFBaWv90CoYu+42f+TElEdoxBunQDzZmA66JSrsfL31Eka3E2WJRT6CQaLt7F5TLihoOxmL2  #
#  6KbQZu9CjHu8OTTPhhnpz8jomS2nf9F1ZslpXtRoYl8fUHO3cEDGSQgtC8nvcMbK5iyDbgRS6G0RWToS6TGA==  #
# ---------------------------------------------------------------------------------------- #
#  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsrtAUhLbs/ELXgH3OJs0SKh7tSQE/gkPavHv4//tsLucTAN  #
#  C4mEjbjxKtFlZjji89GGvatnGu3DvAAz60VNEGBccezdn4rkcNpceKQe2KE2Kb13KM6VmrNl4Gj3+C278u0yKx  #
#  l07WpQCYJ1x6WU8Tnrs5oRSGvHzJVvkxbH7YfymnoXbDg2j8cWYX+zNR/aYvcX+6isZmqRDg+qZ1CK45UL0sO9  #
#  GcSFyey3fGigzWGvBx9JujvsxL6aqX7yY+WtCbApeGLN4HYtrn4ueuKAQND5EYo0SEI2m+STt5eCdDBLFhG0jD  #
#  5MO6T7o//Mg8qDeuiY5wpbcQdpVWmdWQQxMT chuck@kuracali.com                                 #
# ---------------------------------------------------------------------------------------- #
