#!/bin/bash

./acheck $1

if [ $? -eq 0 ]
then
  bash $1
else
  exit 1
fi

# ----Attest-0.1.0------------------------------------------------------------------------ #
#  signed                                                                                  #
#  2018-12-01 11:41:52                                                                     #
# ---------------------------------------------------------------------------------------- #
#  lEltWTJOX2gQMnH4Elync9d7640rwU+/H3tDGUudVnS1OgsXd4f31iNmQlk4MTwiowbH9hqoVX2BWbGKsx1bik  #
#  +Ae+5Lrqe4NfDcQWgbB6IaWuzMA1XZnoR4BH5cKq9T9yv2XTsC1X12NanIJFZbgPfJxACH/u1kbYrL+bawEggI  #
#  oDcStWgSvh8Y+hs9sBu5mUUOGVf7xg+NJIZ9LkLZlojU3dICfLuzmEtht9okx3tCOHdTxLwDkt214dUYXwOSYK  #
#  W+OCGqPbTJv3WuvXC+Y0o/Ptyv+sO6jPgugfy5fJPvUBsqxXve7/PJHH7bW4WjnmcUfgtoio5UgEyqejIorw==  #
# ---------------------------------------------------------------------------------------- #
#  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsrtAUhLbs/ELXgH3OJs0SKh7tSQE/gkPavHv4//tsLucTAN  #
#  C4mEjbjxKtFlZjji89GGvatnGu3DvAAz60VNEGBccezdn4rkcNpceKQe2KE2Kb13KM6VmrNl4Gj3+C278u0yKx  #
#  l07WpQCYJ1x6WU8Tnrs5oRSGvHzJVvkxbH7YfymnoXbDg2j8cWYX+zNR/aYvcX+6isZmqRDg+qZ1CK45UL0sO9  #
#  GcSFyey3fGigzWGvBx9JujvsxL6aqX7yY+WtCbApeGLN4HYtrn4ueuKAQND5EYo0SEI2m+STt5eCdDBLFhG0jD  #
#  5MO6T7o//Mg8qDeuiY5wpbcQdpVWmdWQQxMT chuck@kuracali.com                                 #
# ---------------------------------------------------------------------------------------- #
